---
name: Shairport Sync
version: 1.0.4
slug: shairport_sync
description: AirPlay audio receiver for Home Assistant
url: https://github.com/WangChuDi/addon-shairport-sync
startup: application
init: false
arch:
  - aarch64
  - amd64
boot: auto
hassio_api: true
homeassistant_api: true
host_network: true
audio: true
privileged:
  - SYS_NICE
map:
  - config:rw
options:
  log_level: info
  avahi_interfaces: ""
  avahi_hostname: ""
  avahi_domainname: local
  airplay_name: Home Assistant
  enable_ipv6: false
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  avahi_interfaces: str?
  avahi_hostname: str?
  avahi_domainname: str
  airplay_name: str
  enable_ipv6: bool
